# Change these first
owner: ClemArt # Your GitHub organization or username, where this repository lives
repo: uptime-sq # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: SQ Main backend
    url: $G_BACKEND_SECRET_ENDPOINT
#  - name: Bedrock
#    url: $G_BEDROCK_CHECK_ENDPOINT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.sq.clemart.eu
  # baseUrl: /uptime-sq
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime SQ
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Services below are monitored over HTTP and TCP every 5 min
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  responseTime: "55 * * * *"
